# Sereath's triggers
# Credits: suonho, yewbic, klankbeeld, Trebblofang, PatrickLieberkind, TheDweebMan
# More info in the credits.txt file

[universal]
	fade_in = "100"
    fade_out = "100"
	delay = "200"

# Menu
[p_cpa_415330]
    [p_cpa_415330.trigger]
        name = "menu"
[aftermath]
    [aftermath.trigger]
        name = "menu"
[bluesizzle]
    [bluesizzle.trigger]
        name = "menu"
[nightbreak]
    [nightbreak.trigger]
        name = "menu"

# Night
[k_ha15_137070]
	[k_ha15_137070.trigger]
		name = "time"
		priority = "12"
		start = "night"
		identifier = "night"
[k_ha16_137109]
	[k_ha16_137109.trigger]
		name = "time"
		identifier = "night"
[k_ha54scl_194737]
	[k_ha54scl_194737.trigger]
		name = "time"
		identifier = "night"
[k_ha67_203738]
	[k_ha67_203738.trigger]
		name = "time"
		identifier = "night"
[k_ha70_13052513_211495]
	[k_ha70_13052513_211495.trigger]
		name = "time"
		identifier = "night"
[k_ha50121369_192433]
	[k_ha50121369_192433.trigger]
		name = "time"
		identifier = "night"
[t_etmbl_277192]
	[t_etmbl_277192.trigger]
		name = "time"
		identifier = "night"
[t_se1_178113]
	[t_se1_178113.trigger]
		name = "time"
		identifier = "night"
[thunderdreams]
	[thunderdreams.trigger]
		name = "time"
		identifier = "night"

# Low HP
[s_sv_58962]
    [s_sv_58962.trigger]
        name = "lowhp"
        priority = "14"
        level = "30"
[t_p_173917]
    [t_p_173917.trigger]
        name = "lowhp"
        priority = "14"
        level = "30"

# Dead
[s_asmd_54921]
    [s_asmd_54921.trigger]
        name = "dead"
        priority = "15"
[t_ct_172641]
    [t_ct_172641.trigger]
        name = "dead"
        priority = "15"

# Void
[k_ha41h13022800_180964]
    [k_ha41h13022800_180964.trigger]
        name = "height"
        priority = "16"
        level = "-1"
        identifier = "inVoid"

# Bloodmoon
[k_ha42178043_182115]
    [k_ha42178043_182115.trigger]
        name = "bloodmoon"
        priority = "13"
[k_ha49182111_190687]
    [k_ha49182111_190687.trigger]
        name = "bloodmoon"
        priority = "13"
[k_hev1609250978_367197]
    [k_hev1609250978_367197.trigger]
        name = "bloodmoon"
        priority = "13"