# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
	[[triggers.height]]
		level = "48"
		priority = "4"
		identifier = "underground"
	[[triggers.time]]
		priority = "3"
		time_bundle = "night"
		identifier = "night"
	[[triggers.time]]
		priority = "2"
		time_bundle = "day"
		identifier = "day"
	[triggers.dead]
		priority = "15"
	[triggers.lowhp]
		level = "25"
		priority = "14"
	[[triggers.height]]
		level = "-1"
		priority = "16"
		fade_in = "1"
		identifier = "inVoid"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "1" ]
		identifier = "end"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "-1" ]
		identifier = "nether"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "0" ]
		identifier = "overworld"
	[triggers.bloodmoon]
	[triggers.menu]
	[triggers.universal]
		fade_out = "100"
		persistence = "0"
		trigger_delay = "0"
		song_delay = "200:1000"
		start_delay = "0"
		stop_delay = "0"
		fade_in = "100"
[songs]
	[songs.k_ha7813032200_255715]
		triggers = [ "dimension-overworld" "height-underground" ]
	[[songs.k_ha15_137070]]
		triggers = [ "dimension-overworld" "height-underground" ]
	[[songs.k_ha50121369_192433]]
		triggers = [ "dimension-overworld" "height-underground" ]
	[[songs.k_ha15_137070]]
		volume = "1.3"
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.k_ha16_137109]
		volume = "1.1"
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.k_ha54scl_194737]
		volume = "0.9"
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.k_ha67_203738]
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.k_ha70_13052513_211495]
		triggers = [ "dimension-overworld" "time-night" ]
	[[songs.k_ha50121369_192433]]
		volume = "1.3"
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.t_etmbl_277192]
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.t_se1_178113]
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.thunderdreams]
		volume = "0.9"
		triggers = [ "dimension-overworld" "time-night" ]
	[songs.k_ha41h13022800_180964]
		triggers = [ "height-inVoid" ]
	[songs.t_ct_172641]
		triggers = [ "dead" ]
	[songs.s_asmd_54921]
		triggers = [ "dead" ]
	[songs.t_p_173917]
		triggers = [ "lowhp" ]
	[songs.s_sv_58962]
		triggers = [ "lowhp" ]
	[songs.aftermath]
		triggers = [ "menu" ]
	[songs.bluesizzle]
		triggers = [ "menu" ]
	[songs.nightbreak]
		triggers = [ "menu" ]
	[songs.k_ha14_135836]
		volume = "0.8"
		triggers = [ "dimension-end" ]
	[songs.k_ha7212xcdq_13052514_212045]
		volume = "0.8"
		triggers = [ "dimension-end" ]
	[songs.t_hba_178607]
		volume = "0.8"
		triggers = [ "dimension-end" ]
	[songs.k_ha3813020300_179029]
		triggers = [ "dimension-nether" ]
	[songs.k_ha3713012901_177862]
		triggers = [ "dimension-nether" ]
	[songs.universal]
